version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - npm i --only=prod
    build:
        commands:
            - npm run build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - "build/**/*"
